# Generated by Django 3.1.7 on 2021-04-24 09:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=150, verbose_name='گزینه ۱')),
                ('option2', models.CharField(max_length=150, verbose_name='گزینه ۲')),
                ('option3', models.CharField(blank=True, max_length=150, null=True, verbose_name='گزینه ۳')),
                ('option4', models.CharField(blank=True, max_length=150, null=True, verbose_name='گزینه ۴')),
                ('option5', models.CharField(blank=True, max_length=150, null=True, verbose_name='گزینه ۵')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه درسی')),
            ],
        ),
        migrations.CreateModel(
            name='Fileds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام رشته')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مقطع تحصیلی')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.fileds')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام درس')),
                ('coursegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.coursegroup')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.grades')),
            ],
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوره')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_qu', models.TextField(choices=[('1', 'Multi options'), ('2', 'Descriptive '), ('3', 'True or False'), ('4', 'blank')], max_length=1, verbose_name='نوع سوال')),
                ('text', models.CharField(max_length=250, verbose_name='متن سوال')),
                ('answer_choice', models.CharField(max_length=1)),
                ('answer_text', models.CharField(max_length=150, null=True, verbose_name='متن جواب')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='Questions_img', verbose_name='تصویر سوال')),
                ('question_voice', models.FileField(blank=True, null=True, upload_to='Questions_voice', verbose_name='فایل صوتی سوال')),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='Answer_img', verbose_name='تصویر جواب')),
                ('answer_voice', models.FileField(blank=True, null=True, upload_to='Answer_voice', verbose_name='فایل صوتی جواب')),
                ('hardness', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='درجه سختی')),
                ('source', models.CharField(max_length=100, verbose_name='منبع')),
                ('choices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.choises')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ManyToManyField(to='Question_Bank.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='fileds',
            name='periods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.periods'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام دسته بندی')),
                ('coursegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.coursegroup')),
            ],
        ),
    ]
