# Generated by Django 3.1.7 on 2021-03-27 10:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=150)),
                ('option2', models.CharField(max_length=150)),
                ('option3', models.CharField(max_length=150)),
                ('option4', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Fileds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_qu', models.TextField(choices=[('1', 'Four options'), ('2', 'Descriptive ')], max_length=1)),
                ('text', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Questions img')),
                ('hardness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('source', models.CharField(max_length=100)),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.choises')),
                ('field', models.ManyToManyField(to='Question_Bank.Fileds')),
                ('grade', models.ManyToManyField(to='Question_Bank.Grades')),
                ('period', models.ManyToManyField(to='Question_Bank.Periods')),
            ],
        ),
    ]
