# Generated by Django 3.1.7 on 2021-03-27 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='hardness',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
