# Generated by Django 3.1.7 on 2021-03-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choises',
            name='option3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='choises',
            name='option4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='choises',
            name='option5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
