# Generated by Django 3.1.7 on 2021-04-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Bank', '0002_auto_20210424_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='creator',
            new_name='written_by',
        ),
    ]
