# Generated by Django 3.1.7 on 2021-03-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Bank', '0002_auto_20210327_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Questions_img'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type_qu',
            field=models.TextField(choices=[('1', 'Four options'), ('2', 'Descriptive '), ('3', 'True or False')], max_length=1),
        ),
    ]
