# Generated by Django 3.1.7 on 2021-03-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Bank', '0002_auto_20210328_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_choice',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
